### ISSUE TITLE
RDK Timeliness Monitor error when using moveit2 to control the real rizon4 robotic arm

### ISSUE THREAD

**Issue by AGREATAPE** [flexivrobotics/flexiv_ros2#31] opened 2024-03-21 05:40 UTC
Hi，I am trying to use moveit2 to control the real rizon4 robotic arm, but when I click the excute button to let the robotic arm perform motion, the robotic arm always reports an error. As shown below：
![image](https://github.com/flexivrobotics/flexiv_ros2/assets/37623835/6ddb6523-c08d-46b7-8a7b-f37813800198)
Any solution? Thanks.

**Comment by munseng-flexiv** [comment] 2024-03-21 09:00
@AGREATAPE 

Hello please give us more details about the environment you use e.g. ROS 2 version (Foxy or Humble), Ubuntu OS version, flexiv_ros2 release version, RCA version.

Make sure you follow the steps in the README to  [enable RDK on the robot server](https://rdk.flexiv.com/manual/getting_started.html#activate-rdk-server) and [establish connection](https://rdk.flexiv.com/manual/getting_started.html#establish-connection) between the workstation PC and the robot.

RDK timeliness monitor reports fault if the command messages are not sent to the robot at 1000 Hz.

**Comment by AGREATAPE** [comment] 2024-03-21 09:33
> @AGREATAPE
> 
> Hello please give us more details about the environment you use e.g. ROS 2 version (Foxy or Humble), Ubuntu OS version, flexiv_ros2 release version, RCA version.

@munseng-flexiv 
Hi，my environment is deployed on docker：
ROS2 humble；Ubuntu 22.04.3 LTS；flexiv_ros2 humble v0.9.1; RCA 2.10.8；

> RDK timeliness monitor reports fault if the command messages are not sent to the robot at 1000 Hz.

How do I get the frequency of command messages？I would check this first.

**Comment by munseng-flexiv** [comment] 2024-03-21 09:49
@AGREATAPE 

the update rate of the ros2 controller manager is specified in the [rizon_controllers.yaml](https://github.com/flexivrobotics/flexiv_ros2/blob/humble/flexiv_bringup/config/rizon_controllers.yaml#L3) file. I don't think there's [command line interface](https://control.ros.org/master/doc/ros2_control/ros2controlcli/doc/userdoc.html) to monitor the update rate of the controller (default controller is joint trajectory controller in position interface).

For topic, you can check the publish rate using [ros2 topic hz](https://control.ros.org/master/doc/ros2_control/ros2controlcli/doc/userdoc.html), e.g. 

```
ros2 topic hz /joint_states
```

**Comment by AGREATAPE** [comment] 2024-03-25 03:32
@munseng-flexiv 
The update rate of the ros2 controller manager is specified in the rizon_controllers.yaml file as 1000hz. I used the hz command to check /joint_states, it seems that it is only about 950.  This may be the cause of the problem. Is there any solution?

**Comment by munseng-flexiv** [comment] 2024-03-25 03:40
@AGREATAPE 

Could you reproduce the error in another workstation PC or another environment setup? The latency problem is probably due to the setup environment. 

I tested with the [ROS 2 Humble docker](https://github.com/athackst/vscode_ros2_workspace) and had no problem.

**Comment by AGREATAPE** [comment] 2024-03-25 06:55
@munseng-flexiv 
Yes, I've tried this in two computers and both have similar issues; I deployed the same ROS 2 Humble docker as you tested；
I found some problems after testing：If it is on the host, the update rate can reach a stable 1000hz, but once it is deployed in docker, the update rate will be stable at a random value between 950 ~ 999hz.

**Comment by munseng-flexiv** [comment] 2024-03-25 07:12
@AGREATAPE 

You can refer to the RDK [Establish Connection](https://rdk.flexiv.com/manual/getting_started.html#establish-connection) guide to check the latency complies with the requirement listed in [System Setup](https://rdk.flexiv.com/manual/system_setup.html).

```
ping <robot_ip>
```
The time value from the ping command denotes the round trip latency. For real-time access (ROS 2) to the robot, the round trip latency must be lower than 1 ms.

You can refer to the [Real-time kernel setup](https://rdk.flexiv.com/manual/system_setup.html#real-time-kernel-setup-optional-linux-only) if you want to patch the Linux real-time kernel.

**Comment by AGREATAPE** [comment] 2024-03-25 07:48
@munseng-flexiv 
I checked the round trip latency is 0.2ms;
Now I am even more suspicious that the problem is between ros2，moveit2 and docker, because even if I use fake_system, the problem of decreased update rate still occurs in docker.

**Comment by munseng-flexiv** [comment] 2024-05-08 08:27
Issue closed as the issue is due to the user setup environment. 

The driver is set to use RT mode as default. You can modify the driver to NRT mode by changing the RDK API functions in the `flexiv_hardware/src/flexiv_hardware_interface.cpp` file if your PC is not able to send RT commands in 1 kHz.

- Change the `StreamJointPosition()` to `SendJointPosition()`
- Change the control mode from `RT_JOINT_POSITION` to `NRT_JOINT_POSITION`

**Closed as completed by munseng-flexiv** 2024-05-08 08:27 UTC

**Comment by munseng-flexiv** [comment] 2025-03-19 03:35
Starting [v1.5](https://github.com/flexivrobotics/flexiv_ros2/releases/tag/humble-v1.5), the default control mode is set to NRT (before was RT) in `ros2_control` joint position control. 

The reason is that most users' setup environments are not real-time compatible, and the RDK timeliness error occurs when running ROS2 joint position control in RT mode.
